CREATE TABLE public.pessoa
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    cpf character varying(11) NOT NULL,
    sexo "char",
    email character varying(50),
    data_nascimento date NOT NULL,
    naturalidade text,
    nacionalidade text,
    data_inclusao date NOT NULL,
    data_alteracao date NOT NULL,
    CONSTRAINT pk_pessoa PRIMARY KEY (id),
    CONSTRAINT ui_cpf UNIQUE (cpf),
    CONSTRAINT ck_sexo CHECK (sexo in ('M', 'F'))
);