CREATE TABLE public.usuario
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    nome text NOT NULL,
    senha text NOT NULL,
    ativo integer NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id),
    CONSTRAINT iu_usuario_X_nome UNIQUE (nome)
);

insert into public.usuario(nome, senha, ativo)
values('admin', '$2a$10$5Q8OS4yIV4P8DA02W.N/CODdOM6W0M6CN1GAEiUZLJxEEeVwz.eF6', 1); -- admin@123

CREATE TABLE public.role
(
    id integer NOT NULL,
    nome text NOT NULL,
    CONSTRAINT pk_role PRIMARY KEY (id),
    CONSTRAINT iu_role_x_nome UNIQUE (nome)
);

insert into public.role(id, nome)
values(1, 'MANAGER'),
      (2, 'USER');

CREATE TABLE public.usuario_role
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    id_usuario integer NOT NULL,
    id_role integer NOT NULL,
    CONSTRAINT pk_usuario_role PRIMARY KEY (id),
    CONSTRAINT iu_usuario_role UNIQUE (id_usuario, id_role),
    CONSTRAINT fk_usuario_role_x_usuario FOREIGN KEY (id_usuario)
        REFERENCES public.usuario (id),
    CONSTRAINT fk_usuario_role_x_role FOREIGN KEY (id_role)
        REFERENCES public.role (id)
);

insert into public.usuario_role(id_usuario, id_role)
values(1, 1),
      (1, 2);