version: '3.0'

services:
  desafio-tecnico-db:
    container_name: desafio-tecnico-db
    hostname: desafio-tecnico-db
    image: postgres:latest
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: "desafiotecnico"
      POSTGRES_PASSWORD: "PW@234"
      POSTGRES_DB: "desafiotecnico"

  desafio-tecnico-api:
    container_name: desafio-tecnico-api
    hostname: desafio-tecnico-api
    image: gilsomanfredi/desafio-tecnico-softplan-backend:latest
    ports:
      - "8585:8080"
    environment:
      JAVA_OPTS: "-Dserver.port=8080 -Dspring.datasource.url=jdbc:postgresql://desafio-tecnico-db:5432/desafiotecnico -Dspring.datasource.username=desafiotecnico -Dspring.datasource.password=PW@234"
    links:
      - desafio-tecnico-db
  
  desafio-tecnico-ui:
    container_name: desafio-tecnico-ui
    hostname: desafio-tecnico-ui
    image: gilsomanfredi/desafio-tecnico-softplan-frontend:latest
  
  desafio-tecnico-nginx:
    container_name: desafio-tecnico-nginx
    hostname: desafio-tecnico-nginx
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "81:80/tcp"
    links:
      - desafio-tecnico-ui
      - desafio-tecnico-api