version: '3.0'

services:
  postgres:
    container_name: desafiotecnico-db
    hostname: desafiotecnico-db
    image: postgres:latest
    ports:
      - "6543:5432"
    environment:
      POSTGRES_USER: "desafiotecnico"
      POSTGRES_PASSWORD: "PW@234"
      POSTGRES_DB: "desafiotecnico"
#    volumes:
#      - ./postgresql/data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin4:
    container_name: pgadmin4
    hostname: pgadmin4
    image: dpage/pgadmin4
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "pgadmin4@postgres"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin4@234"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge